### ISSUE TITLE
PackageNotFoundError: tidypolars

### ISSUE THREAD

**Issue by mjkarlsen** [markfairbanks/tidypolars#16]
In `__init__.py`, it looks for the installed version of tidypolars, however if it hasn't been previously installed it throws a `PackageNotFoundError` error. One work around is to comment block the script in `__init__.py` and then `import tidypolars`.  Then uncomment block the script in `__init__.py`, restart the kernel, and then `import tidypolars`.  

I _attempted_ to fix in a new branch "update-init".

#14 Removing `numpy` would also help the initial import of `tidypolars`. That was another error that was thrown since I didn't have `numpy` installed on my test env. I doubt this would be a problem since most users have `numpy`. This is not something I addressed in the new branch "update-init".

**Comment by markfairbanks** [comment]
This should only be a dec isshe

**For regular users**
If you run `pip3 install tidypolars` everything should work as intended (including numpy being downloaded)

**For devs**
You need to run `poetry install` as mentioned in here
