### ISSUE TITLE
Add installation through conda

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidypolars#203]
Now that `polars` is available through conda, `tidypolars` can be added.

**Comment by nsandau** [comment]
First of all, thanks for this excellent package!

I have created a PR adding tidypolars to conda-forge:  #https://github.com/conda-forge/staged-recipes/pull/20328
Would you mind being added as a recipe maintainer?

**Comment by markfairbanks** [comment]
> I have created a PR adding tidypolars to conda-forge

Thanks 🥳 

> Would you mind being added as a recipe maintainer?

That sounds good to me!

I'll be honest I'm not very familiar with how the conda-forge process works. I'll look more into it, but if there's anything you need me to do let me know.

**Comment by markfairbanks** [comment]
Awesome - thanks again @nsandau 😄
