### ISSUE TITLE
Compatibility with polars v0.14.0

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidypolars#207]
PR that caused the break: https://github.com/pola-rs/polars/pull/4309

Old behavior that tidypolars relied on: https://github.com/pola-rs/polars/pull/2862

**Comment by markfairbanks** [comment]
@grantmcdermott - FYI I just uploaded tidypolars v0.2.17 to PyPi that is compatible with polars >=0.14.0

**Comment by grantmcdermott** [comment]
Super, thanks Mark. Looking forward to giving this a spin.
