### ISSUE TITLE
idiomatic way to add list as column

### ISSUE THREAD

**Issue by eutwt** [markfairbanks/tidypolars#213]
Forgive what's probably a dumb question, but is there a way to get `.mutate` to return the same object as the `.bind_cols` line?

```python
import tidypolars as tp

tb = tp.Tibble({'a': [1, 2, 3]})
x = [4, 5, 6]
# gives desired output 
tb.bind_cols(tp.Tibble({'b': x}))
# gives error: ValueError: could not convert value '[4, 5, 6]' as a Literal
tb.mutate(b = x)
```

**Comment by eutwt** [comment]
Closing because I learned from #158 that this works:

```python
tb.mutate(b = tp.lit(tp.Series(x)))
```

Thanks for the package!

**Comment by markfairbanks** [comment]
> Actually my previous comment had an uneccesary `tp.lit()`. Just `tb.mutate(b = tp.Series(x))` works

Now that I think about it this is probably "correct" functionality, so I'll close this.
