### ISSUE TITLE
`write_csv()` returns `'super' object has no attribute 'to_csv'`

### ISSUE THREAD

**Issue by alesvomacka** [markfairbanks/tidypolars#219]
Hi,
There seems to be a problem with `write_csv()`. I can import tidypolars and the data just fine:

    import tidypolars as tp
    
    rents = tp.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-07-05/rent.csv")

But when I try to export the data frame as a csv file:

    rents.write_csv("rents.csv")

I get an error stating `'super' object has no attribute 'to_csv'`.

The data come from the [Tidytuesday repo](https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-07-05). Python version is 3.10.8 and tidypolars is 0.2.19. I'm on macOS 13.

**Comment by markfairbanks** [comment]
Thanks for catching this - looks like `polars` deprecated `.to_csv()`. I'll update `tidypolars` to fix this.

**Comment by markfairbanks** [comment]
This has been fixed
