### ISSUE TITLE
Python 3.11 compatibility/availability?

### ISSUE THREAD

**Issue by exsell-jc** [markfairbanks/tidypolars#230]
Just checked other branches, and it seems the other branches are not for dev.

Just wondering what the latest would be on updates.

Also, wanted to put this interesting + recent `tidypandas` to attention. I thought you might like their solution to the `col('NAME')` situation. https://www.youtube.com/watch?v=AMJEnkA0YrE though I'm assuming because it's Python dictionary, perhaps it would suffer on performance?

**Comment by lindblb** [comment]
2nd this

**Comment by hmhensen** [comment]
Long update times for tidypolars make it difficult for me to rely on polars.

**Comment by markfairbanks** [comment]
> Long update times for tidypolars make it difficult for me to rely on polars.

`polars` has been implementing changes (and breaking changes) faster than I can keep up with. Changing `reverse` to `descending` in `.sort()` was one of them. It's good that `polars` is constantly improving, but the API instability makes it a bit hard to build a package that depends on it unfortunately.

There are probably a lot more fixes necessary to get `tidypolars` back to a good state. I'll try to get to them at some point, but between a newborn and a new job I'm bit behind on keeping this package up to date. I've only had enough time lately to keep updates to R's `tidytable` and `dtplyr`.

**Comment by exsell-jc** [comment]
Hey @markfairbanks, double congrats! :)

Thanks for keeping us in the loop. No worries about it for now.

**Comment by hmhensen** [comment]
I understand, that makes sense. Congrats on the kid! Hopefully, polars matures soon and the changes start coming slower. You've done a great job on your package.
________________________________

**Comment by cboettig** [comment]
:tada: :tada:
