### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by P-Courtney** [markfairbanks/tidypolars#232]
Does tidypolars work on apple silicon in R studio? I have loaded via pip and I get the following: 

> library(tidypolars)
Error: package or namespace load failed for ‘tidypolars’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/pcourt/Library/R/arm64/4.3/library/polars/libs/polars.so':
  dlopen(/Users/pcourt/Library/R/arm64/4.3/library/polars/libs/polars.so, 0x0006): tried: '/Users/pcourt/Library/R/arm64/4.3/library/polars/libs/polars.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/pcourt/Library/R/arm64/4.3/library/polars/libs/polars.so' (no such file), '/Users/pcourt/Library/R/arm64/4.3/library/polars/libs/polars.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
In addition: Warning message:
package ‘tidypolars’ was built under R version 4.3.1 
> 

(Apologies if this is a noob q)

**Comment by markfairbanks** [comment]
I think you're looking for the R version of `tidypolars` found here: https://github.com/etiennebacher/tidypolars

This is the python version.
