### ISSUE TITLE
The following argument(s) will not be used: `ignore.case` in grepl

### ISSUE THREAD

**Issue by DDHGITHUB** [markfairbanks/tidypolars#234]
I use grepl inside a mutate case_when a lot.
I almost always use the argument ignore.case=T to select both upper and lower case.
Ie grepl("excele",kind,ignore.case = T)==T~"Excelerate", T ~ "something else"

Is it possible to add the ignore.case argument to the grepl function ?

Thanks.

**Comment by markfairbanks** [comment]
Are you opening this in the right repository? There is no `grepl()` function currently.
