### ISSUE TITLE
Remove Tibble subclass and create `tp` or `r` namespace

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidypolars#238]
We can use the extension API to create a custom namespace for tidypolars methods that work directly on polars DataFrames and Expressions.

Open to suggestions on whether to use `tp` or `r` as the namespace.

```python
import polars as pl
from polars import col
import tidypolars as tp

df = pl.DataFrame({"x": range(3), "y": ["a", "a", "b"]})

(
    df
    .tp.arrange("x")
    .tp.summarize(x_mean = col("x").tp.mean(),
                  _by = "y")
)
```

**Comment by markfairbanks** [comment]
There's also the option of adding the `tp`/`r` namespace while keeping the Tibble subclass and giving users the ability to use whichever they prefer. Not sure if that's the right way to go though.

**Comment by kdpsingh** [comment]
Is there any functionality you would like to keep in how data frames are defined or in how metadata are maintained (eg for logging purposes) that would be important to maintain within the Tibble subclass and would otherwise be tough to intermingle with regular polars DataFrames?

If not, could consider soft-deprecating Tibble unless you discover a need for it.

**Comment by kdpsingh** [comment]
Actually, I kind of like the idea of keeping the subclass for now. I honestly think that as long as there is a `from_polars()` and `to_polars()` method, I probably would try to stay within the tidypolars syntax, and having the subclass would save a bunch of `tp.***` calls to make it slightly cleaner.

**Comment by markfairbanks** [comment]
Yep - the subclass makes things a bit cleaner. The DataFrame namespace option however gives access to a lot of the other "extra" goodies provided by polars - compatibility with external libraries like sklearn and plotting being the main ones.

The `.tp.` addition can get a little annoying, which was why I was debating the `.r.` namespace. It's less typing and would be a bit cleaner.

```python
(
    df
    .r.arrange("x")
    .r.summarize(x_mean = pl.col("x").r.mean(),
                  _by = "y")
)
```

**Comment by kdpsingh** [comment]
Why tidyverse definitely originated from R, including `r` in a Python package makes it seem somehow less idiomatic in Python. With the namespace route, I still prefer `tp` over `r` bc it gives it identity. Just my 2 cents, so feel free to do as you as you see fit.

**Comment by kdpsingh** [comment]
Bump :-)

**Comment by markfairbanks** [comment]
I think I'm just going to keep the Tibble subclass
