### ISSUE TITLE
Any plans for the R version of tidypolars?

### ISSUE THREAD

**Issue by erdeyl** [markfairbanks/tidypolars#266]
Hi Mark,

I'm sorry for asking it here. Do you have any plans for tidypolars for R? Would it make any sense to develop it at all?

Best,

Laszlo

**Comment by markfairbanks** [comment]
Hey Laszlo - looks like this was already built by another user.

https://github.com/etiennebacher/tidypolars

**Comment by erdeyl** [comment]
Thank you, Mark. I prefer the philosophy you follow with tidytable, but I surely understand you. However, if you decide to develop something like it your way, many people will be happy.

I appreciate your great work.

Thankfully, 

Laszlo
