### ISSUE TITLE
as_pandas give error

### ISSUE THREAD

**Issue by fkgruber** [markfairbanks/tidypolars#270]
I installed tidypolars 0.3.0 from the repository but when I do:

```
import tidypolars as tp
from tidypolars import col, desc
df = tp.tibble(x = range(3), y = range(3, 6), z = ['a', 'a', 'b'])
df.as_pandas()
```

I get:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/user/miniconda3/envs/int_algo_utils_5/lib/python3.11/site-packages/tidypolars/tibble_df.py", line 886, in as_pandas
>     return super().to_pandas()
>            ^^^^^^^^^^^^^^^^^^^
>   File "/Users/user/miniconda3/envs/int_algo_utils_5/lib/python3.11/site-packages/polars/dataframe/frame.py", line 2398, in to_pandas
>     return self._to_pandas_without_object_columns(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/user/miniconda3/envs/int_algo_utils_5/lib/python3.11/site-packages/polars/dataframe/frame.py", line 2446, in _to_pandas_without_object_columns
>     if not df.width:  # Empty dataframe, cannot infer schema from batches
>            ^^^^^^^^
>   File "/Users/user/miniconda3/envs/int_algo_utils_5/lib/python3.11/site-packages/tidypolars/tibble_df.py", line 83, in __getattribute__
>     raise AttributeError
> AttributeError

Weird thing is that I can go from polars to pandas:
`df.as_polars().to_pandas()`

>    x  y  z
> 0  0  3  a
> 1  1  4  a
> 2  2  5  b

**Comment by markfairbanks** [comment]
All fixed, thanks for catching this.

```python
import tidypolars as tp

df = tp.tibble(x = [1, 2, 3], y = ["a", "a", "b"])

type(df.as_pandas())
```

```
pandas.core.frame.DataFrame
```

**Comment by markfairbanks** [comment]
Also FYI - `0.3.0` is now installable using `pip install tidypolars`
