### ISSUE TITLE
Class name: tidyframe, TidyFrame, tibble, or Tibble

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidypolars#9]
Which one should we go with?

**Comment by mjkarlsen** [comment]
My top two are: 
1. tidyframe 
2. tibble 

Snakecase drives me nuts 🤣

**Comment by markfairbanks** [comment]
> Snakecase drives me nuts

Lol me too. That’s typical class naming conventions.

I am leaning tibble at the moment. tidyframe made more sense when that was the package name. If we go tidyframe I think it’d make more sense to go TidyFrame to tie it to `pl.DataFrame` logically in a user’s head
