### ISSUE TITLE
Update docs to use expression functions instead of methods

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidypolars#94]
Needs updating:
* `.filter()`
* `.summarize.()`
* `example.ipynb`

Might be others as well.

**Comment by mjkarlsen** [comment]
I'll take care of these examples once #117  is closed. I'm assuming that you want examples like the ones below added to the existing examples.  

**Filter**
```
df = tp.Tibble({'a': range(3), 'b': ['a', 'a', 'b']})
df.filter(col('a') >= tp.mean(col('a')))
```
**Summarize**
```
df = tp.Tibble({'a': range(3), 'b': range(3), 'c': ['a', 'a', 'b']})
df.summarize(avg_a = tp.mean(col('a')))
```

**Comment by markfairbanks** [comment]
> I'm assuming that you want examples like the ones below added to the existing examples.

I was also thinking we should drop the examples that uses methods like `col('x').mean()`
